version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.prod
    ports:
      - "3000:3000"
    environment:
      - VITE_API_URL=http://backend:8080
    depends_on:
      - backend

  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.prod
    ports:
      - "8080:8080"
    depends_on:
      - database
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=yourpassword
      - DB_NAME=speech_scape
      - DB_PORT=3306
      #- CORS_ORIGIN=https://localhost:3000
      - NODE_ENV=production

  database:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=yourpassword
      - MYSQL_DATABASE=speech_scape
    ports:
      - "3306:3306"
    volumes:
      - db_data:/var/lib/mysql

volumes:
  db_data:
