version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      -./client:/app
      - /app/node_modules
    environment:
      - VITE_API_URL=http://backend:8080
  
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - database
    environment:
      - DB_HOST=db
      - DB_USER=root
      - DB_PASSWORD=root
      - DB_NAME=speech_scape
      - DB_PORT=3306
      - CORS_ORIGIN=http://localhost:3000

  database:
    image: mysql:latest
    restart: always
    environment:
      - MYSQL_ROOT_PASSWORD=root
      - MYSQL_DATABASE=speech_scape
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  db_data: