services:
  client:
    build:
      context: ./client
      dockerfile: Dockerfile.client
    ports:
      - "3000:3000"
    env_file:
      - client/.env

  server:
    build:
      context: ./server
      dockerfile: Dockerfile
    ports:
      - "8080:8080"
    depends_on:
      - database
    env_file:
      - server/.env

  database:
    image: mysql:8.0
    environment:
      MYSQL_ROOT_PASSWORD: root
      MYSQL_DATABASE: speechscape
    ports:
      - "3306:3306"
