version: "3.8"

services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      -./client:/app
      - /app/node_modules
    env_file:
      - fileName: .env.dev
  
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - database
    env_file:
      - fileName: .env.dev

  database:
    image: mysql:latest
    restart: always
    env_file:
      - fileName: .env.dev
    ports:
      - "3306:3306"
    volumes:
      - ./mysql:/var/lib/mysql

volumes:
  db_data: