services:
  frontend:
    build:
      context: ./client
      dockerfile: Dockerfile.dev
    ports:
      - "3000:3000"
    volumes:
      - ./client:/app
      - /app/node_modules
    env_file:
      - client/.env.dev
    networks:
      - app-network
  
  backend:
    build:
      context: ./server
      dockerfile: Dockerfile.dev
    ports:
      - "8080:8080"
    volumes:
      - ./server:/app
      - /app/node_modules
    depends_on:
      - database
    env_file:
      - server/.env.dev
    networks:
      - app-network

  database:
    image: mysql:latest
    restart: always
    env_file:
      - server/.env.dev
    ports:
      - "3307:3306"
    volumes:
      - db_data:/var/lib/mysql
      - ./speech_scape.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network

volumes:
  db_data:

networks:
  app-network:
    driver: bridge