services:
  client:
    volumes:
      - ./client:/app
      - node_modules:/app/node_modules
    command: ["npm", "run", "dev"]

  server:
    volumes:
      - ./server:/var/www/html
      - node_modules_server:/var/www/html/node_modules
    command: ["npm", "run", "dev"]

volumes:
  node_modules:
  node_modules_server: