name: Integration Tests

on:
  pull_request:
    branches: [develop, main]

jobs:
  integration-tests:
    name: Run Full System Tests
    runs-on: ubuntu-latest

    services:
      mysql:
        image: mysql:8.0
        env:
          MYSQL_ROOT_PASSWORD: root
          MYSQL_DATABASE: speechscape_test
          MYSQL_USER: test_user
          MYSQL_PASSWORD: test_password
        ports:
          - 3306:3306
        options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3

    steps:
      - uses: actions/checkout@v3

      - name: Set Up Docker Compose
        run: docker-compose -f docker-compose.override.yml up -d

      - name: Run Integration Tests
        run: npm run test:integration
