name: Integration Tests

on:
    pull_request:
        branches: [ development, main ]

jobs:
    integration-tests:
        runs-on: ubuntu-latest
        services:
            mysql:
                image: mysql:latest
                env:
                    MYSQL_ROOT_PASSWORD: root
                    MYSQL_DATABASE: speech_scape
                ports:
                    - 3306:3306
                options: --health-cmd="mysqladmin ping" --health-interval=10s --health-timeout=5s --health-retries=3
        
        steps:
            - uses: actions/checkout@v4

            - name: Build & start services
              run: docker-compose -f docker-compose.dev.yml up -d --build
            
            - name: Run API tests
              run: |
                curl -s http://localhost:8080/api/health || exit 1
            
            - name: Stop Services
              run: docker-compose -f docker-compose.dev.yml down

    #TODO: Deployment